### ISSUE TITLE
RNG Helper instances persists in Task Manager

### ISSUE THREAD

**Issue by Hoishin** [roostalol/RNGHelper#25] opened 2017-08-06 09:17 UTC
![2017-08-06_18-11-30](https://user-images.githubusercontent.com/28832095/29002007-3ea68734-7ad3-11e7-92c9-d3295c2b89e8.gif)
What I basically did:
1. Open OBS Studio and RNG Helper
2. Add RNG Helper from Window Source
3. Change Helper to Steal/Rare
4. Close RNG Helper
You get one Penelo for one set of this procedure

**Comment by erickt420** [comment] 2017-08-06 09:23
Repro Steps:

1) Open RNG Helper
2) Change Helper to Steal/Rare
3) Close RNG Helper

Expected: Process should exit.
Actual: Zombie process persists.

**Comment by erickt420** [comment] 2017-08-06 11:35
Root Cause:
Only the Main Form aka, The first form launched by the Application automatically closes the program when it is closed. Other forms do not do this automatically.

Solution:
Add EventHandler for Form.OnClosed to exit the application.

Fix is in CR, #27 .

**Closed as completed** 2017-08-07 02:30 UTC
Labels: bug
